vich_uploader:
    db_driver: orm

    mappings:
        products_image:
            uri_prefix: /media/products
            upload_destination: '%kernel.project_dir%/public/media/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        category_image:
            uri_prefix: /media/category
            upload_destination: '%kernel.project_dir%/public/media/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
