easy_admin:
    list:
        max_results: 30
    site_name: '%shop_name%'
    design:
        menu:
            - label: 'Products'
              icon: 'cubes'
              children:
                - { entity: 'Products', icon: 'cube', default: true, label: Products List}
            - label: 'Categories'
              icon: 'tags'
              children:
                - { entity: 'Category', icon: 'tag'}
                - { entity: 'SubCategory', icon: 'tag'}
            - label: 'Users'
              icon : 'id-card'
              children:
                - { entity: 'User', icon: 'user', label: Users List }
    formats:
        date: 'd/m/Y'