easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - "id"
                    - { property: 'picture', type: 'image', base_path : '/media/category'}
                    - "name"
            form:
                fields:
                    - { property: 'imgfile', type: 'vich_image', label: 'Image'}
                    - "name"