easy_admin:
    entities:
        Products:
            class: App\Entity\Products
            list:
                fields:
                    - "id"
                    - "Enabled"
                    - { property: 'picture.filename', type: 'image', base_path: '/media/products/' }
                    - "name"
                    - "Price"
                    - { property: 'created_at', type: 'date'}
                    - "tags"
                    - "subcategory"
                    - "sku"
            show:
                fields:
                    - "id"
                    - "Enabled"
                    - { property: 'picture.filename', type: 'image',base_path: '/media/products/' }
                    - "name"
                    - "Price"
                    - { property: 'created_at', type: 'date'}
                    - "tags"
                    - "subcategory"
                    - "sku"
            form:
                fields:
                    - { property: 'Enabled', type: 'checkbox', label: 'Activé'}
                    - { property: 'Quantity', type: 'integer', label: 'Quantité'}
                    - { property: 'Name', type: 'text', label: 'Nom du produit'}
                    - { property: 'Price', type: 'integer', label: 'Prix'}
                    - { property: 'subcategory', label: 'Sous catégorie'}
                    - { property: 'tags', label: 'Mots clé'}
                    - { property: 'sku', type: 'integer', label: 'SKU produit'}
                    - { property: 'pictureFiles', type: 'collection', label: 'Images', multiple : 'multiples', accept: 'image/*', type_options: {entry_type : 'file'}}