easy_admin:
    entities:
        Products:
            class: App\Entity\Products
            list:
                fields:
                    - "id"
                    - "Enabled"
                    - { property: 'picture.filename', type: 'image', base_path: '/media/products/' }
                    - "name"
                    - "Price"
                    - { property: 'created_at', type: 'date'}
                    - "tags"
                    - "subcategory"
                    - "sku"
            show:
                fields:
                    - "id"
                    - "Enabled"
                    - { property: 'picture.filename', type: 'image',base_path: '/media/products/' }
                    - "name"
                    - "Price"
                    - { property: 'created_at', type: 'date'}
                    - "tags"
                    - "subcategory"
                    - "sku"
            form:
                fields:
                    - { property: 'Enabled', type: 'checkbox'}
                    - "name"
                    - { property: 'Price', type: 'integer'}
                    - "subcategory"
                    - "tags"
                    - { property: 'sku', type: 'integer'}
                    - { property: 'pictureFiles', type: 'collection', label: 'Image', multiple : 'multiple', accept: 'image/*', type_options: {entry_type : 'file'}}