easy_admin:
    entities:
        Products:
            class: App\Entity\Products
            list:
                fields:
                    - "id"
                    - "Enabled"
                    - { property: 'picture.filename', type: 'image', base_path: '/media/products/' }
                    - "Name"
                    - "Price"
                    - { property: 'created_at', type: 'date'}
                    - "Tags"
                    - "Sku"
            show:
                fields:
                    - "ID"
                    - "Enabled"
                    - { property: 'picture.filename', type: 'image',base_path: '/media/products/' }
                    - "Name"
                    - "Price"
                    - { property: 'created_at', type: 'date'}
                    - "Tags"
                    - "Sku"
            form:
                fields:
                    - { property: 'Enabled', type: 'checkbox', label: 'is Enabled'}
                    - { property: 'Quantity', type: 'integer', label: 'Quantity'}
                    - { property: 'Name', type: 'text', label: 'Product Name'}
                    - { property: 'Price', type: 'integer', label: 'Price'}
                    - { property: 'tags', type: 'text', label: 'Keywords'}
                    - { property: 'categories', label: 'Categories'}
                    - { property: 'sku', type: 'integer', label: 'SKU product'}
                    - { property: 'pictureFiles', type: 'collection', label: 'Images', multiple : 'multiples', accept: 'image/*', type_options: {entry_type : 'file'}}