easy_admin:
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\Admin\AdminController
            form:
                fields:
                    - { property: 'password', type: 'password', label: 'Password'}
                    - { property: 'confirmPassword', type: 'password', label: 'Confirme Password'}
                    # - { property: 'roles', type: 'choice', type_options: { choices: { 'ROLE_USER': 'User', 'ROLE_ADMIN': 'Admin' } }, label: 'User Role'}