easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields: 
                    - "username"
                    - "roles" 
                    - "password"