easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - "isEnabled"
                    - "username"
                    - "roles" 
                    - "uuid"
            form:
                fields:
                    - { property: 'username', type: 'text', label: 'Username'}
                    - { property: 'email', type: 'email', label: 'Email'}
                    - { property: 'password', type: 'password', label: 'Password'}
                    - { property: 'confirmPassword', type: 'password', label: 'Confirme Password'}
                    # - { property: 'roles', type: 'choice', type_options: { choices: { 'ROLE_USER': 'User', 'ROLE_ADMIN': 'Admin' } }, label: 'User Role'}