easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - "isEnabled"
                    - "isConfirmed"
                    - "username"
                    - "roles" 
                    - "uid"